name: build

on: [pull_request, push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.0.x]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up node modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node${{ matrix.node-version }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-node${{ matrix.node-version }}-build-
            ${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          touch .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > .npmrc
          echo "@onur1:registry=https://npm.pkg.github.com" >> .npmrc
          npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
